name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  playwright:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci
      working-directory: frontend/

    - name: Install backend dependencies
      run: npm ci
      working-directory: backend/

    - name: Start backend server
      run: npm run dev &
      working-directory: backend/
      env:
        MONGODB_URI: mongodb://localhost:27017/test_database_ci

    - name: Wait for backend to be ready
      run: npx wait-on http://localhost:5000/api/users/login --timeout 60000
      working-directory: frontend/

    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      working-directory: frontend/

    - name: Run Playwright tests
      run: npx playwright test frontend/tests
      working-directory: frontend/
