name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  playwright:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:8.0
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci
      working-directory: frontend/

    - name: Install backend dependencies
      run: npm ci
      working-directory: backend/

    - name: Start backend server
      run: npm run dev &
      working-directory: backend/
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
    
    - name: Debug Secret
      run:
        echo "DEBUG_SECRET_RAW_PARTIAL=$(echo '${{ secrets.MONGO_URI }}' | head -c 5)"
        

    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      working-directory: frontend/

    - name: Run Playwright login test
      run: npx playwright test login.spec.js
      working-directory: frontend/
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}

    - name: Run Playwright register test
      run: npx playwright test register.spec.js
      working-directory: frontend/
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}

    - name: Run Playwright profile test
      run: npx playwright test profile.spec.js
      working-directory: frontend/
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
    
    - name: Run Playwright home test
      run: npx playwright test home.spec.js
      working-directory: frontend/
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
    
    - name: Run Playwright clubs test
      run: npx playwright test clubs.spec.js
      working-directory: frontend/
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
    
    - name: Run Playwright meets test
      run: npx playwright test meets.spec.js
      working-directory: frontend/
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}